### Label Encoding
Label encoding and original encoding are two techniques used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to teach category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories. For example, if we have a categorical variable color with three possible values (red, green, blue), we can represent it using label encoding as follows:

1. Red: 1
2. Green: 2
3. Blue: 3

In [2]:
import pandas as pd

In [3]:
#create a simple dataframe
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [6]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [8]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\Zobayer\.conda\envs\python_eda\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [9]:
lbl_encoder.transform([['red']])

c:\Users\Zobayer\.conda\envs\python_eda\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [10]:
lbl_encoder.transform([['blue']])

c:\Users\Zobayer\.conda\envs\python_eda\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [11]:
lbl_encoder.transform([['green']])

c:\Users\Zobayer\.conda\envs\python_eda\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

### Ordinal Encoding

It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value based on its position in the order. For example, if we have a categorical variable 'education level' with four possible values (high school, college, graduate, post-graduate), we can represent it using ordinal encoding as follows

1. High School: 1
2. College: 2
3. Graduate: 3
4. Post-Graduate: 4

In [12]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [13]:
df = pd.DataFrame({
    'size': ['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [14]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [15]:
## create instance of ordinal and then  fit_transform
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [16]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [17]:
encoder.transform([['small']])

c:\Users\Zobayer\.conda\envs\python_eda\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])